config/routes.rb
Bhcouriers::Application.routes.draw do

  resources :pages

  resources :home
  resources :services
  resources :about_us
  resources :contact_us
  resources :testimonials
  resources :pages
  
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"


end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @page = Page.find_by_page_type("about_us")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @page }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @page = Page.find_by_page_type("contact_us")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @page }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @page = Page.find_by_page_type("home")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @page }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])
    @testimonials = Testimonial.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
    @testimonials = Testimonial.all
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])
    @testimonials = Testimonial.all
    
    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @page = Page.find_by_page_type("services")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @page }
    end
  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  # GET /testimonails
  # GET /testimonails.json
  def index
    @page = Page.find_by_page_type("testimonials")
    @testimonials = Testimonial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @testimonails }
    end
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/about_us/index.html.erb
<%= render 'shared/header' %>
<%= render 'shared/nav' %>  


<div class="container">
  <div class="row">
    <div class="span12"> 
      
      <div class="hero-unit">
        <div class="page-header">
          <h2><%= @page.page_header %></h2>
        </div>
        
        <p><%= @page.paragraph_1 %></p>      
        <%= image_tag("P1030370.JPG", :width=>"200px", :height=>"150px") %>
        <br/>      
        <br/>
        <p><%= @page.paragraph_2 %></p>
        <%= image_tag("P1030035.JPG", :width=>"200px", :height=>"150px") %>
        <br/>
        <br/>
        <br/>
      
        <div>
          <h3><span class="add-on"><i class="icon-map-marker"></i></span> <%= @page.three_heading_1 %></h3>
          <address>
            <%= @page.address_line_1 %><br>
            <%= @page.address_line_2 %><br>
            <%= @page.address_line_3 %><br>
          </address>
          <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="<%= @page.link_1.html_safe %>"</iframe>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>  

app/views/contact_us/index.html.erb
<%= render 'shared/header' %>
<%= render 'shared/nav' %>  


<div class="container">
  <div class="row">
    <div class="span12"> 

      <div class="hero-unit">
        <div class="page-header">
          <h2><%= @page.page_header %></h2>
        </div>
        
        <div>
          <h3><span class="add-on"><i class="icon-envelope-alt"></i></span> <%= @page.three_heading_1 %></h3>
          <h6><%= @page.six_heading_1 %></h6>
          <a href="mailto:<%= @page.email_1 %>"><%= @page.email_1 %></a>
          <br/><br/>
          <h6><%= @page.six_heading_2 %></h6>
          <p><a href="mailto:<%= @page.email_2 %>"><%= @page.email_2 %></a></p>
          <p><a href="mailto:<%= @page.email_3 %>"><%= @page.email_3 %></a></p>
          <p><a href="mailto:<%= @page.email_4 %>"><%= @page.email_4 %></a></p>
        </div>
        <br/>
      
        <div>
          <h3><span class="add-on"><i class="icon-phone"></i></span>  <%= @page.three_heading_2 %></h3>
          <h6><%= @page.six_heading_3 %></h6>
          <p><%= @page.paragraph_1 %></p>
          <h6><%= @page.six_heading_4 %></h6>
          <p><%= @page.paragraph_2 %></p>
          <p><%= @page.paragraph_3 %></p>
          <p><%= @page.paragraph_4 %></p>
        </div>
        <br/>
        
        <div>
          <h3><span class="add-on"><i class="icon-home"></i></span>  <%= @page.three_heading_3 %></h3>
          <address>
            <%= @page.address_line_1 %><br>
            <%= @page.address_line_2 %><br>
            <%= @page.address_line_3 %><br>
          </address>
      </div>
      
    </div>
  </div>
</div>

<%= render 'shared/footer' %>  

app/views/home/index.html.erb
<%= render 'shared/header' %>
<%= render 'shared/nav' %>  

<div class="container">
  <div class="row">
    <div class="span12"> 
         
      <div class="hero-unit">
        <div class="page-header">
          <h1><small><%= @page.paragraph_1 %></small></h1>
        </div>
      </div>      
      
    </div>
  </div>
</div>

<%= render 'shared/footer' %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BH Couriers</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>
  <!-- Empty Tw Bootstrap modal div -->  
  <div class="modal hide fade" id="modal-window">
  </div>
  <%= yield %>
 </body>
</html>

app/views/pages/_about_us.html.erb
<div class='row'>
  <div class="span8">
    <fieldset class='well fields'>
      <h2><span class="add-on"><i class="icon-pencil"></i></span> Edit - About Us Page</h2>
      <br/>
    
      <div class="control-group">
        <%= f.label :page_header, "Page header", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :page_header %>
        </div>
      </div>
          
      <div class="control-group">
        <%= f.label :paragraph_1, "Paragraph 1", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_area :paragraph_1 %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :paragraph_2, "Paragraph 2", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_area :paragraph_2 %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label :three_heading_1, "Location heading", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :three_heading_1 %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :address_line_1, "Address line 1", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :address_line_1 %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label :address_line_2, "Address line 2", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :address_line_2 %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label :address_line_3, "Address line 3", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :address_line_3 %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :link_1, "Map Link", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_area :link_1 %>
        </div>
      </div>
      
      <%= f.submit 'Save Changes', :class => 'btn btn-large btn-success' %>                  
    </fieldset>

  </div>
</div>

app/views/pages/_contact_us.html.erb
<div class='row'>
  <div class='span8'>
    <fieldset class='well fields'>
      
      <h2><span class="add-on"><i class="icon-pencil"></i></span> Edit - Contact Us Page</h2>
      <br/>
    
      <div class="control-group">
        <%= f.label :page_header, "Page header", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :page_header %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label :three_heading_1, "Main heading 1", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :three_heading_1 %>
        </div>
      </div>
            
      <div class="control-group">
        <%= f.label :six_heading_1, "Email heading 1", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :six_heading_1 %>
        </div>
      </div>
            
      <div class="control-group">
        <%= f.label :email_1, "Email 1", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :email_1 %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label :six_heading_2, "Email heading 2", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :six_heading_2 %>
        </div>
      </div>
            
      <div class="control-group">
        <%= f.label :email_2, "Email 2", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :email_2 %>
        </div>
      </div>
            
      <div class="control-group">
        <%= f.label :email_3, "Email 3", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :email_3 %>
        </div>
      </div>
            
      <div class="control-group">
        <%= f.label :email_4, "Email 4", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :email_4 %>
        </div>
      </div>
      
 
      
      <div class="control-group">
        <%= f.label :three_heading_2, "Main heading 2", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :three_heading_2 %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label :six_heading_3, "Telephone heading 1", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :six_heading_3 %>
        </div>
      </div>
            
      <div class="control-group">
        <%= f.label :paragraph_1, "Telephone 1", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :paragraph_1 %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label :six_heading_4, "Telephone heading 2", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :six_heading_4 %>
        </div>
      </div>
            
      <div class="control-group">
        <%= f.label :paragraph_2, "Telephone 2", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :paragraph_2 %>
        </div>
      </div>
            
      <div class="control-group">
        <%= f.label :paragraph_3, "Telephone 3", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :paragraph_3 %>
        </div>
      </div>
            
      <div class="control-group">
        <%= f.label :paragraph_4, "Telephone 4", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :paragraph_4 %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label :three_heading_3, "Main heading 3", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :three_heading_3 %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label :address_line_1, "Address line 1", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :address_line_1 %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label :address_line_2, "Address line 2", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :address_line_2 %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label :address_line_3, "Address line 3", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :address_line_3 %>
        </div>
      </div>
      
      <%= f.submit 'Save Changes', :class => 'btn btn-large btn-success' %>
   
    </fieldset>
  </div>
</div>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <%= render @page.page_type, :f => f %>
      

<% end %>

app/views/pages/_home.html.erb
<div class='row'>
  <div class='span8'>
    <fieldset class='well fields'>
      
      <h2><span class="add-on"><i class="icon-pencil"></i></span> Edit - Home Page</h2>
      <br/>
    
      <div class="control-group">
        <%= f.label :paragraph_1, "Paragraph 1", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_area :paragraph_1 %>
        </div>
      </div>

      <%= f.submit 'Save Changes', :class => 'btn btn-large btn-success' %>      
    </fieldset> 

  </div>
</div>

app/views/pages/_services.html.erb
<div class='row'>
  <div class='span8'>
    <fieldset  class='well fields'>
      <h2><span class="add-on"><i class="icon-pencil"></i></span> Edit - Services Page</h2>
      <br/>

      <div class="control-group">
        <%= f.label :page_header, "Page header", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :page_header %>
        </div>
      </div>
          
      <div class="control-group">
        <%= f.label :paragraph_1, "Paragraph 1", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_area :paragraph_1 %>
        </div>
      </div>
      
      <%= f.submit 'Save Changes', :class => 'btn btn-large btn-success' %>
    </fieldset>
  </div>
</div>

app/views/pages/_testimonial_fields.html.erb
<fieldset>

  <div class="control-group">
    <%= f.label :customer_info, "Customer information", :class=>'control-label'%>
    <div class="controls">
      <%= f.text_field :customer_info %>
    </div>
  </div>
      
  <div class="control-group">
    <%= f.label :customer_testimonial, "Testimonial", :class=>'control-label'%>
    <div class="controls">
      <%= f.text_area :customer_testimonial %>
    </div>
  </div>
  
  <br/>
  <br/>
  
</fieldset>

app/views/pages/_testimonials.html.erb
<div class='row'>
  <div class='span8'>
  
    <fieldset class='well fields'>
      <h2><span class="add-on"><i class="icon-pencil"></i></span> Edit - Testimonials Page</h2>
      
      <br/>
    
      <div class="control-group">
        <%= f.label :page_header, "Page header", :class=>'control-label'%>
        <div class="controls">
          <%= f.text_field :page_header %>
        </div>
      </div>
      
        <%= f.fields_for @testimonials do |builder| %>
          <%= render 'testimonial_fields', :f => builder %>
        <% end %>

      <%= f.submit 'Save Changes', :class => 'btn btn-large btn-success' %>            
    </fieldset>
    
  </div>
</div>

app/views/pages/edit.html.erb
<%= render 'shared/header' %>
<%= render 'shared/nav' %>  

<div class="container">
  <div class="row">
    <%= render 'shared/sidenav' %>  
    <div class="span9"> 
      <%= render 'form' %> 
      
    </div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/pages/show.html.erb
<%= render 'shared/header' %>
<%= render 'shared/nav' %>  

<div class="container">
  <div class="row">
    <%= render 'shared/sidenav' %>  

    <div class="span8 well fields"> 
    
      <% if @page.page_type == "home" %>
        <h2><span class="add-on"><i class="icon-file"></i></span> View - Home Page</h2>
        <br/>
        <p>
          <b>Paragraph 1:</b><br/>
          <%= @page.paragraph_1 %>
        </p>
        
      <% elsif @page.page_type == "services" %>
        <h2><span class="add-on"><i class="icon-file"></i></span> View - Services Page</h2>
        <br/>
        <p>
          <b>Page header:</b><br/>
          <%= @page.page_header %>
        </p>
        <p>
          <b>Paragraph 1:</b><br/>
          <%= @page.paragraph_1 %>
        </p>
        
      <% elsif @page.page_type == "about_us" %>
        <h2><span class="add-on"><i class="icon-file"></i></span> View - About Us Page</h2>
        <br/>
        <p>
          <b>Page header:</b><br/>
          <%= @page.page_header %>
        </p>
        <p>
          <b>Paragraph 1:</b><br/>
          <%= @page.paragraph_1 %>
        </p>        
        <p>
          <b>Paragraph 2:</b><br/>
          <%= @page.paragraph_2 %>
        </p>
        <p>
          <b>Location heading:</b><br/>
          <%= @page.three_heading_1 %>
        </p>
        <p>
          <b>Address line 1:</b><br/>
          <%= @page.address_line_1 %>
        </p>
        <p>
          <b>Address line 2:</b><br/>
          <%= @page.address_line_2 %>
        </p>
        <p>
          <b>Address line 3:</b><br/>
          <%= @page.address_line_3 %>
        </p>
        <p>
          <b>Map Link:</b><br/>
          <%= @page.link_1 %>
        </p>

      <% elsif @page.page_type == "testimonials" %>
        <h2><span class="add-on"><i class="icon-file"></i></span> View - Testimonials Page</h2>
        <br/>
        <p>
          <b>Page header:</b><br/>
          <%= @page.page_header %>
        </p>
        <!--<p>
          <b>Customer information:</b><br/>
          <%= @page.customer_info %>
        </p>
        <p>
          <b>Testimonial:</b><br/>
          <%= @page.customer_testimonial %>
        </p>-->
        
      <% elsif @page.page_type == "contact_us" %>
        <h2><span class="add-on"><i class="icon-file"></i></span> View - Contact Us Page</h2>
        <br/>
        <p>
          <b>Page header:</b><br/>
          <%= @page.page_header %>
        </p>
        <p>
          <b>Main heading 1:</b><br/>
          <%= @page.three_heading_1 %>
        </p>
        <p>
          <b>Email heading 1:</b><br/>
          <%= @page.six_heading_1 %>
        </p>
        <p>
          <b>Email 1:</b><br/>
          <%= @page.email_1 %>
        </p>
        <p>
          <b>Email heading 2:</b><br/>
          <%= @page.six_heading_2 %>
        </p>
        <p>
          <b>Email 2:</b><br/>
          <%= @page.email_2 %>
        </p>
        <p>
          <b>Email 3:</b><br/>
          <%= @page.email_3 %>
        </p>
         <p>
          <b>Email 4:</b><br/>
          <%= @page.email_4 %>
        </p>             
        <p>
          <b>Main heading 2:</b><br/>
          <%= @page.three_heading_2 %>
        </p>
        <p>
          <b>Telephone heading 1:</b><br/>
          <%= @page.six_heading_3 %>
        </p>
        <p>
          <b>Telephone 1:</b><br/>
          <%= @page.paragraph_1 %>
        </p>
        <p>
          <b>Telephone heading 2:</b><br/>
          <%= @page.six_heading_4 %>
        </p>
        <p>
          <b>Telephone 2:</b><br/>
          <%= @page.paragraph_2 %>
        </p>
        <p>
          <b>Telephone 3:</b><br/>
          <%= @page.paragraph_3 %>
        </p>
        <p>
          <b>Telephone 4:</b><br/>
          <%= @page.paragraph_4 %>
        </p>    
        
        <p>
          <b>Main heading 3:</b><br/>
          <%= @page.three_heading_3 %>
        </p>   
        <p>
          <b>Address line 1:</b><br/>
          <%= @page.address_line_1 %>
        </p>
        <p>
          <b>Address line 2:</b><br/>
          <%= @page.address_line_2 %>
        </p>
        <p>
          <b>Address line 3:</b><br/>
          <%= @page.address_line_3 %>
        </p>
        
      <% end %> 
    
      <%= link_to 'Edit', edit_page_path(@page), :class => 'btn btn-primary btn-large' %>
    </div>

  </div>
</div>

<%= render 'shared/footer' %>

app/views/services/index.html.erb
<%= render 'shared/header' %>
<%= render 'shared/nav' %>  


<div class="container">
  <div class="row">
    <div class="span12"> 
      
      <div class="hero-unit">
        <div class="page-header">
          <h2><%= @page.page_header %></h2>
        </div>
        <p><%= @page.paragraph_1 %></p>
      </div>
      
    </div>
  </div>
</div>

<%= render 'shared/footer' %>  

app/views/shared/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <hr/>
      <footer>
        <h6>Created by Bitformed 2012</h6>
      </footer>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="container">
  <div class="row">
    <div class="span12"> 
      <div class="hero-unit">
        <div class="main-logo">
          <h1>BH Couriers  <small> For all of your storage and delivery needs  <small/>
            <span class="add-on"><i class="icon-truck"></i></span>  
            <span class="add-on"><i class="icon-truck"></i></span>  
            <span class="add-on"><i class="icon-truck"></i></span>  
          </h1>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
    
      <div class="nav-collapse" id="main-menu">
        <ul class="nav" id="main-menu-left">
          <li class="<%= 'active' if params[:controller] == 'home' %>"> <a href="/home">Home</a> </li>
          <li class="<%= 'active' if params[:controller] == 'services' %>"> <a href="/services">Services</a> </li>
          <li class="<%= 'active' if params[:controller] == 'about_us' %>"> <a href="/about_us">About Us</a> </li>
          <li class="<%= 'active' if params[:controller] == 'testimonials' %>"> <a href="/testimonials">Testimonials</a> </li>
          <li class="<%= 'active' if params[:controller] == 'contact_us' %>"> <a href="/contact_us">Contact Us</a> </li>
          <li class="divider-vertical"></li>

          <li class="<%= 'active' if params[:controller] == 'pages' %>"> <a href="/pages/<%= Page.find_by_page_type("home").id %>">Admin<span class="add-on"><i class="icon-paper-clip"></i></span></a> </li>
        </ul>
      </div>
       
    </div>
  </div>
</div>

app/views/shared/_sidenav.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Admin</li>
        <li> <a href="/pages/<%= Page.find_by_page_type("home").id %>">Home</a> </li>
        <li> <a href="/pages/<%= Page.find_by_page_type("services").id %>">Services</a> </li>
        <li> <a href="/pages/<%= Page.find_by_page_type("about_us").id %>">About Us</a> </li>
        <li> <a href="/pages/<%= Page.find_by_page_type("testimonials").id %>">Testimonials</a> </li>
        <li> <a href="/pages/<%= Page.find_by_page_type("contact_us").id %>">Contact Us</a> </li>
    </ul>
  </div>
</div>

<!--<li class="<%= 'active' if params[:controller] == 'home' %>"> <a href="/pages/1/edit">Home</a> </li>-->

app/views/testimonials/index.html.erb
<%= render 'shared/header' %>
<%= render 'shared/nav' %>  


<div class="container">
  <div class="row">
    <div class="span12"> 
      
      <div class="hero-unit">
        <div class="page-header">
          <h2><%= @page.page_header %></h2>
        </div>
        
        <% @testimonials.each do |testimonial| %>
          <% unless testimonial.customer_info.blank? %>
            <h6><%= testimonial.customer_info %></h6>
            <p><%= testimonial.customer_testimonial %></p>      
            <br/>      
            <br/>
          <% end %>
        <% end %>

      </div>
      
    </div>
  </div>
</div>


<%= render 'shared/footer' %>  